### PR TITLE
Added a note about Audio problems

### PR DESCRIPTION
**Pull request by nopmop**

### CODE REVIEW

**Comment by iqacevedo** [comment]
thanks! it works

**Comment by nopmop** [comment]
@iqacevedo do you have problems with the microphone?

**Comment by iqacevedo** [comment]
Yes, I had not noticed because I always use headphones.

**Comment by jrandiny** [comment]
Yea, this fix seems to break mic input. I'm still investigating. And it seems that the broken sound is caused by some software in the userland and not because of kernel update

**Comment by nopmop** [comment]
@jrandiny @iqacevedo I've fixed it already on kernel `5.8.0-26-generic`. I will explain what I've figured out: if you check: `lspci -v | grep -A6 -E '(Audio|Multimedia)' you will see that the Multimedia Controller (which handles the microphone) is managed by the Renoir kernel module, while the the rest of the audio subsystem is handled by Intel-HDA. Now, this last subsystem is split in two controllers (try: `cat /proc/asound/cards'), so the conflict happens when `snd_intel_hda` wrongly detects the speakers in position 0 as default (which is detected as SPDIF out, but I think it's really the HDMI out) and so since pulseaudio gets the default alsa device it ends up showing as `Dummy Output` (no audio).

**The solution** is actually simpler than I thought: 
- remove the `blacklist snd_acp3x_rn` from `/etc/modprobe.d/blacklist.conf` which I had originally devised for this PR
- add `options snd-hda-intel index=1` to `/etc/modprobe.d/alsa-base.conf`. 

As I was just setting up the laptop, I missed the microphone problem - I apologize. In the meantime, for other reasons, I decided to upgrade to ubuntu 20.10 and the stock kernel `5.8.0-26-generic` and everything works. Proof: 

image

If you can confirm this solution works for you too I'll issue another PR.

**Comment by jrandiny** [comment]
It works, but I need to test the HDMI audio first

**Comment by jrandiny** [comment]
Bad news, HDMI audio doesn't work. It seems that your solution is forcing the Intel driver to handle the device which resulted in the "HD Audio generic" device.

In addition, I have created issue #9 for discussing this issue

**Pull request merged**
